export const clientLogos = [
    {
      id: 1,
      name: "Director General of Immigration Passports",
      image: "/images/clients/dgip.png",
      width: 200,
      height: 200,
    },
    {
      id: 2,
      name: "Ministry of Petroleum and Natural Resources",
      image: "/images/clients/petroleum.png",
      width: 200,
      height: 200,
    },
    {
      id: 3,
      name: "Ministry of Finance",
      image: "/images/clients/finance.png",
      width: 200,
      height: 200,
    },
    {
      id: 4,
      name: "Oil & Gas Development Company Limited",
      image: "/images/clients/ogdcl.png",
      width: 200,
      height: 200,
    },
    {
      id: 5,
      name: "Pakistan Cricket Board",
      image: "/images/clients/pcb.png",
      width: 200,
      height: 200,
    },
    {
      id: 6,
      name: "Pakistan Air Force",
      image: "/images/clients/paf.png",
      width: 200,
      height: 200,
    },
    {
      id: 7,
      name: "Pakistan Navy",
      image: "/images/clients/navy.png",
      width: 200,
      height: 200,
    },
    {
      id: 8,
      name: "Pakistan Atomic Energy Commission",
      image: "/images/clients/atomic.png",
      width: 200,
      height: 200,
    },
    {
      id: 9,
      name: "National Telecom Corporation",
      image: "/images/clients/ntc.png",
      width: 200,
      height: 200,
    },
    {
      id: 10,
      name: "Pakistan Information Technology Company",
      image: "/images/clients/pitc.png",
      width: 200,
      height: 200,
    },
    {
      id: 17,
      name: "Ufone",
      image: "/images/clients/Ufone.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 18,
      name: "Telenor",
      image: "/images/clients/Telenor_Pakistan.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 19,
      name: "K-Electric",
      image: "/images/clients/K_Electric.png",
      width: 200,
      height: 200,
    },
    {
      id: 20,
      name: "General Electric",
      image: "/images/clients/General_Electric.png",
      width: 200,
      height: 200,
    },
    {
      id: 21,
      name: "Parco",
      image: "/images/clients/Parco.png",
      width: 200,
      height: 200,
    },
    {
      id: 22,
      name: "Highnoon Laboratories",
      image: "/images/clients/Highnoon_Laboratories.png",
      width: 200,
      height: 200,
    },
    {
      id: 23,
      name: "Honda Point",
      image: "/images/clients/Honda_Point.png",
      width: 200,
      height: 200,
    },
    {
      id: 24,
      name: "Habib Construction Services",
      image: "/images/clients/Habib_Construction.png",
      width: 200,
      height: 200,
    },
    {
      id: 25,
      name: "Pepsi",
      image: "/images/clients/Pepsi.png",
      width: 200,
      height: 200,
    },
    {
      id: 26,
      name: "IKEA",
      image: "/images/clients/IKEA_Trading.png",
      width: 200,
      height: 200,
    },
    {
      id: 27,
      name: "International School of Pakistan",
      image: "/images/clients/International_School_of_Islamabad.png",
      width: 200,
      height: 200,
    },
    {
      id: 28,
      name: "Karachi School of Business & Leadership",
      image: "/images/clients/KSBL.png",
      width: 200,
      height: 200,
    },
    {
      id: 29,
      name: "National University of Sciences & Technology",
      image: "/images/clients/NUST.png",
      width: 200,
      height: 200,
    },
    {
      id: 30,
      name: "Quaid-i-Azam University",
      image: "/images/clients/QAU.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 31,
      name: "Punjab University",
      image: "/images/clients/PU.jpg",
      width: 200,
      height: 200,
    }, 
    {
      id: 32,
      name: "Mehar Collection",
      image: "/images/clients/Mehar_Garments.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 33,
      name: "Master Enterprises",
      image: "/images/clients/Master_Tiles.png",
      width: 200,
      height: 200,
    },
    {
      id: 34,
      name: "Marubeni",
      image: "/images/clients/Marubeni.png",
      width: 200,
      height: 200,
    },
    {
      id: 35,
      name: "Khaadi",
      image: "/images/clients/Khaadi.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 36,
      name: "Lotte",
      image: "/images/clients/Lotte.png",
      width: 200,
      height: 200,
    },
    {
      id: 37,
      name: "Mahmood Group",
      image: "/images/clients/Mehmood_Group.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 38,
      name: "Millat Tractors",
      image: "/images/clients/Millat_Tractors.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 39,
      name: "Nexus Technologies",
      image: "/images/clients/Nexus_Technologies.png",
      width: 200,
      height: 200,
    },
    {
      id: 40,
      name: "PKLI",
      image: "/images/clients/PKLI.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 41,
      name: "Polanis Group",
      image: "/images/clients/Polanis.png",
      width: 200,
      height: 200,
    },
    {
      id: 42,
      name: "Quick Links",
      image: "/images/clients/Quick_Links.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 43,
      name: "Redco",
      image: "/images/clients/Redco.png",
      width: 200,
      height: 200,
    },
    {
      id: 44,
      name: "Regency Inn",
      image: "/images/clients/Regency_Inn.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 45,
      name: "The Residency Hotels",
      image: "/images/clients/Residency_Hotel.png",
      width: 200,
      height: 200,
    }, 
    {
      id: 46,
      name: "Global Network",
      image: "/images/clients/Riaz_Bottlers.png",
      width: 200,
      height: 200,
    },
    {
      id: 47,
      name: "RAS School",
      image: "/images/clients/RAS.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 48,
      name: "Rupali Foods",
      image: "/images/clients/Rupali_foods.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 49,
      name: "Shamim & Co",
      image: "/images/clients/Shamim_Co.png",
      width: 200,
      height: 200,
    },
    {
      id: 50,
      name: "Soorty Enterprises",
      image: "/images/clients/Soorty.png",
      width: 200,
      height: 200,
    },
    {
      id: 51,
      name: "JDW Group",
      image: "/images/clients/JDW.png",
      width: 200,
      height: 200,
    },
    {
      id: 52,
      name: "Sukh Chayn Residence",
      image: "/images/clients/Sukh_Chayn.png",
      width: 200,
      height: 200,
    },
    {
      id: 53,
      name: "TA Group",
      image: "/images/clients/TA_Group.png",
      width: 200,
      height: 200,
    },
    {
      id: 54,
      name: "Aman Foundation",
      image: "/images/clients/Aman_Foundation.png",
      width: 200,
      height: 200,
    },
    {
      id: 55,
      name: "The Educators",
      image: "/images/clients/The_Educators.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 56,
      name: "Treet Group",
      image: "/images/clients/Treet_Corp.png",
      width: 200,
      height: 200,
    },
    {
      id: 57,
      name: "UCH Power",
      image: "/images/clients/Uch_Power.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 58,
      name: "Vantage",
      image: "/images/clients/Vantage.jpg",
      width: 200,
      height: 200,
    },
    {
      id: 59,
      name: "Wakgas",
      image: "/images/clients/Wakgas.png",
      width: 200,
      height: 200,
    },
    {
      id: 60,
      name: "WPP",
      image: "/images/clients/WPP.png",
      width: 200,
      height: 200,
    }
  ];