export const partnerLogos = [
    {
      id: 1,
      name: "Barracuda",
      image: "/images/partners/barracuda.png",
      width: 200,
      height: 200,
    },
    {
      id: 2,
      name: "Dell",
      image: "/images/partners/dell.png",
      width: 200,
      height: 200,
    },
    {
      id: 3,
      name: "Cisco",
      image: "/images/partners/cisco.png",
      width: 200,
      height: 200,
    },
    {
      id: 4,
      name: "Fortinet",
      image: "/images/partners/fortinet.png",
      width: 200,
      height: 200,
    },
    {
      id: 5,
      name: "Juniper Networks",
      image: "/images/partners/juniper.png",
      width: 200,
      height: 200,
    },
    {
      id: 6,
      name: "Ruckus",
      image: "/images/partners/ruskus.png",
      width: 200,
      height: 200,
    },
    {
      id: 7,
      name: "SonicWall",
      image: "/images/partners/sonicWall.png",
      width: 200,
      height: 200,
    },
    {
      id: 8,
      name: "Nexthink",
      image: "/images/partners/nexthink.png",
      width: 200,
      height: 200,
    },
    {
        id: 9,
        name: "RedHat",
        image: "/images/partners/redhat.png",
        width: 200,
        height: 200,
      },
      {
        id: 10,
        name: "Huawei",
        image: "/images/partners/huawei.jpg",
        width: 200,
        height: 200,
      },
      {
        id: 11,
        name: "Avaya",
        image: "/images/partners/avaya.png",
        width: 200,
        height: 200,
      },
      {
        id: 12,
        name: "Globitel",
        image: "/images/partners/globitel.png",
        width: 200,
        height: 200,
      },
      {
        id: 13,
        name: "Informatica",
        image: "/images/partners/informatica.jpg",
        width: 200,
        height: 200,
      },
      {
        id: 14,
        name: "Microsoft",
        image: "/images/partners/microsoft.jpg",
        width: 200,
        height: 200,
      }
  ];