export const partnerLogos = [
    {
      id: 1,
      name: "Barracuda",
      image: "/images/partners/barracuda.png",
      width: 200,
      height: 200,
    },
    {
      id: 2,
      name: "Dell",
      image: "/images/partners/dell.png",
      width: 200,
      height: 200,
    },
    {
      id: 3,
      name: "Cisco",
      image: "/images/partners/cisco.png",
      width: 200,
      height: 200,
    },
    {
      id: 4,
      name: "Fortinet",
      image: "/images/partners/fortinet.png",
      width: 200,
      height: 200,
    },
    {
      id: 5,
      name: "Juniper Networks",
      image: "/images/partners/juniper.png",
      width: 200,
      height: 200,
    },
    {
      id: 7,
      name: "SonicWall",
      image: "/images/partners/sonicWall.png",
      width: 200,
      height: 200,
    },
    {
      id: 8,
      name: "Nexthink",
      image: "/images/partners/nexthink.png",
      width: 200,
      height: 200,
    },
    {
        id: 9,
        name: "RedHat",
        image: "/images/partners/redhat.png",
        width: 200,
        height: 200,
      },
      {
        id: 10,
        name: "Huawei",
        image: "/images/partners/huawei.jpg",
        width: 200,
        height: 200,
      },
      {
        id: 11,
        name: "Avaya",
        image: "/images/partners/avaya.png",
        width: 200,
        height: 200,
      },
      {
        id: 13,
        name: "Informatica",
        image: "/images/partners/informatica.jpg",
        width: 200,
        height: 200,
      },
      {
        id: 14,
        name: "Microsoft",
        image: "/images/partners/microsoft.jpg",
        width: 200,
        height: 200,
      },
      {
        id: 15,
        name: "[PIA]",
        image: "/images/partners/Pia.png",
        width: 200,
        height: 200,
      },
      {
        id: 17,
        name: "[Intellica]",
        image: "/images/partners/Intellica.png",
        width: 200,
        height: 200,
      },
      {
        id: 18,
        name: "[Sophos]",
        image: "/images/partners/sophos.png",
        width: 200,
        height: 200,
      },
      {
        id: 20,
        name: "[IFDM]",
        image: "/images/partners/ifdm.png",
        width: 200,
        height: 200,
      },
      {
        id: 21,
        name: "[Itdm]",
        image: "/images/partners/itdm.png",
        width: 200,
        height: 200,
      },
      {
        id: 22,
        name: "[Supermicro]",
        image: "/images/partners/supermicro.png",
        width: 200,
        height: 200,
      },
      {
        id: 24,
        name: "[Lenovo]",
        image: "/images/partners/lenovo.png",
        width: 200,
        height: 200,
      },
      {
        id: 25,
        name: "[VmWare]",
        image: "/images/partners/vmware.png",
        width: 200,
        height: 200,
      },
      {
        id: 27,
        name: "[Veeam]",
        image: "/images/partners/veeam.png",
        width: 200,
        height: 200,
      },
      {
        id: 28,
        name: "[Retable]",
        image: "/images/partners/retable.png",
        width: 200,
        height: 200,
      },
      {
        id: 29,
        name: "[Ivanti]",
        image: "/images/partners/ivanti.png",
        width: 200,
        height: 200,
      },
      {
        id: 30,
        name: "[Evam]",
        image: "/images/partners/evam.png",
        width: 200,
        height: 200,
      },
      {
        id: 31,
        name: "[Kobil]",
        image: "/images/partners/kobil.png",
        width: 200,
        height: 200,
      },
      {
        id: 35,
        name: "[Ruckus]",
        image: "/images/partners/ruckus.png",
        width: 200,
        height: 200,
      },
      {
        id: 36,
        name: "[Workfusion]",
        image: "/images/partners/Workfusion.png",
        width: 200,
        height: 200,
      },
      {
        id: 37,
        name: "[Denxt]",
        image: "/images/partners/denxt.png",
        width: 200,
        height: 200,
      },
  ];