name: Deploy Next.js site to Pages

on:
  push:
    branches: ["gh-pages"]  # Trigger on pushes to gh-pages
  workflow_dispatch:  # Allows manual triggering from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Specify your Node.js version

      - name: Install dependencies
        run: npm install  # or yarn install if you're using Yarn

      - name: Build with Next.js
        run: npm run build  # Ensure this matches your build command

      - name: Export Next.js site
        run: npm run export  # This generates the static files

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          path: ./out  # Ensure this matches your output directory
